FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install --no-audit --no-fund && \
    npm install -D tailwindcss postcss autoprefixer
COPY . .
EXPOSE 5173
CMD ["sh", "-c", "npx vite --host"]